# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('titre', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('categorie', models.CharField(choices=[('POL', 'Politique'), ('SOC', 'Societe'), ('ECO', 'Economie'), ('CUL', 'Culture'), ('SPO', 'Sport'), ('INT', 'Interview'), ('ENI', 'En image'), ('LUP', 'Lu pour vous')], max_length=3)),
                ('contenu', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='depeche',
            options={'ordering': ['heure']},
        ),
        migrations.AlterField(
            model_name='depeche',
            name='titre',
            field=models.CharField(max_length=50),
        ),
    ]
