# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20160330_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(choices=[('P', 'Politique'), ('S', 'Societe'), ('E', 'Economie'), ('C', 'Culture'), ('S', 'Sport'), ('I', 'Interview'), ('N', 'En image'), ('L', 'Lu pour vous')], max_length=3),
        ),
    ]
